/**
 * A pool of demo MCQs, clearly and permanently labeled source_name="Demo"
 * (never presented as scraped content — spec section 28). The demo adapter
 * (./demo.ts) hands out a batch of these per extraction run so that
 * clicking "Extract New MCQs" repeatedly demonstrates the real pipeline —
 * validation, relevance filtering, duplicate detection, saving — actually
 * finding new questions run after run, then correctly reporting "no new
 * relevant MCQs" once the pool is exhausted. It is NOT a substitute for the
 * 15 real source adapters; it exists so the app is fully testable with
 * zero external dependencies.
 */
import type { RawScrapedMcq } from "./base";

export const DEMO_POOL: RawScrapedMcq[] = [
  { sourceQuestionId: "demo-001", question: "Who is regarded as the founder of Pakistan?", optionA: "Liaquat Ali Khan", optionB: "Muhammad Ali Jinnah", optionC: "Allama Iqbal", optionD: "Sir Syed Ahmad Khan", rawAnswerText: "Answer: B", subjectHint: "Pakistan Studies", sourceUrl: "https://example-demo.local/mcq/demo-001" },
  { sourceQuestionId: "demo-002", question: "Pakistan's national language is:", optionA: "Punjabi", optionB: "Sindhi", optionC: "Urdu", optionD: "Pashto", rawAnswerText: "Correct Answer: Urdu", subjectHint: "Pakistan Studies", sourceUrl: "https://example-demo.local/mcq/demo-002" },
  { sourceQuestionId: "demo-003", question: "Which key combination is used to copy selected text in most Windows applications?", optionA: "Ctrl + V", optionB: "Ctrl + X", optionC: "Ctrl + C", optionD: "Ctrl + Z", rawAnswerText: "Ans: C", subjectHint: "Computer Science / IT", sourceUrl: "https://example-demo.local/mcq/demo-003" },
  { sourceQuestionId: "demo-004", question: "The shortcut key to open a new blank workbook in MS Excel is:", optionA: "Ctrl + O", optionB: "Ctrl + N", optionC: "Ctrl + S", optionD: "Ctrl + P", rawAnswerText: "Correct: Option B", subjectHint: "Computer Science / IT", sourceUrl: "https://example-demo.local/mcq/demo-004" },
  { sourceQuestionId: "demo-005", question: "Which gas do plants absorb from the atmosphere for photosynthesis?", optionA: "Oxygen", optionB: "Nitrogen", optionC: "Carbon dioxide", optionD: "Hydrogen", rawAnswerText: "Answer: C", subjectHint: "Everyday Science", sourceUrl: "https://example-demo.local/mcq/demo-005" },
  { sourceQuestionId: "demo-006", question: "The human body's largest organ is the:", optionA: "Liver", optionB: "Heart", optionC: "Skin", optionD: "Lung", rawAnswerText: "Answer: C", subjectHint: "Everyday Science", sourceUrl: "https://example-demo.local/mcq/demo-006" },
  { sourceQuestionId: "demo-007", question: "Choose the correctly spelled word.", optionA: "Recieve", optionB: "Receive", optionC: "Receeve", optionD: "Receve", rawAnswerText: "Ans: B", subjectHint: "English", sourceUrl: "https://example-demo.local/mcq/demo-007" },
  { sourceQuestionId: "demo-008", question: "Choose the correct synonym of \"Abundant\".", optionA: "Scarce", optionB: "Plentiful", optionC: "Rare", optionD: "Limited", rawAnswerText: "Answer: B", subjectHint: "English", sourceUrl: "https://example-demo.local/mcq/demo-008" },
  { sourceQuestionId: "demo-009", question: "If a train travels 60 km in 45 minutes, its speed in km/h is:", optionA: "70", optionB: "75", optionC: "80", optionD: "85", rawAnswerText: "Answer: C", subjectHint: "Basic Mathematics", sourceUrl: "https://example-demo.local/mcq/demo-009" },
  { sourceQuestionId: "demo-010", question: "What is 15% of 400?", optionA: "45", optionB: "60", optionC: "50", optionD: "65", rawAnswerText: "Ans: B", subjectHint: "Basic Mathematics", sourceUrl: "https://example-demo.local/mcq/demo-010" },
  { sourceQuestionId: "demo-011", question: "The Constitution of Pakistan was adopted in which year?", optionA: "1956", optionB: "1962", optionC: "1973", optionD: "1985", rawAnswerText: "Correct Answer: 1973", subjectHint: "Pakistan Studies", sourceUrl: "https://example-demo.local/mcq/demo-011" },
  { sourceQuestionId: "demo-012", question: "Which of these is an input device?", optionA: "Monitor", optionB: "Printer", optionC: "Keyboard", optionD: "Speaker", rawAnswerText: "Answer: C", subjectHint: "Computer Science / IT", sourceUrl: "https://example-demo.local/mcq/demo-012" },
  { sourceQuestionId: "demo-013", question: "Find the odd one out.", optionA: "Apple", optionB: "Banana", optionC: "Carrot", optionD: "Mango", rawAnswerText: "Answer: C", subjectHint: "Basic Analytical Reasoning", sourceUrl: "https://example-demo.local/mcq/demo-013" },
  { sourceQuestionId: "demo-014", question: "Complete the series: 2, 4, 8, 16, __", optionA: "24", optionB: "30", optionC: "32", optionD: "36", rawAnswerText: "Ans: C", subjectHint: "Basic Analytical Reasoning", sourceUrl: "https://example-demo.local/mcq/demo-014" },
  { sourceQuestionId: "demo-015", question: "Who was the first Prime Minister of Pakistan?", optionA: "Liaquat Ali Khan", optionB: "Muhammad Ali Jinnah", optionC: "Feroz Khan Noon", optionD: "Huseyn Shaheed Suhrawardy", rawAnswerText: "Correct: Option A", subjectHint: "Pakistan Studies", sourceUrl: "https://example-demo.local/mcq/demo-015" },
  { sourceQuestionId: "demo-016", question: "The World Wide Web was invented by:", optionA: "Bill Gates", optionB: "Steve Jobs", optionC: "Tim Berners-Lee", optionD: "Mark Zuckerberg", rawAnswerText: "Answer: C", subjectHint: "Computer Science / IT", sourceUrl: "https://example-demo.local/mcq/demo-016" },
  { sourceQuestionId: "demo-017", question: "Which surah of the Quran is known as the heart of the Quran?", optionA: "Surah Al-Fatiha", optionB: "Surah Yaseen", optionC: "Surah Al-Ikhlas", optionD: "Surah Al-Baqarah", rawAnswerText: "Answer: B", subjectHint: "Islamiat / Ethics", sourceUrl: "https://example-demo.local/mcq/demo-017" },
  { sourceQuestionId: "demo-018", question: "How many pillars of Islam are there?", optionA: "Four", optionB: "Five", optionC: "Six", optionD: "Seven", rawAnswerText: "Ans: B", subjectHint: "Islamiat / Ethics", sourceUrl: "https://example-demo.local/mcq/demo-018" },
  { sourceQuestionId: "demo-019", question: "The currency of Pakistan is the:", optionA: "Rupee", optionB: "Taka", optionC: "Dinar", optionD: "Riyal", rawAnswerText: "Answer: A", subjectHint: "Pakistan Studies", sourceUrl: "https://example-demo.local/mcq/demo-019" },
  { sourceQuestionId: "demo-020", question: "In MS Word, which shortcut applies bold formatting to selected text?", optionA: "Ctrl + I", optionB: "Ctrl + U", optionC: "Ctrl + B", optionD: "Ctrl + D", rawAnswerText: "Correct: Option C", subjectHint: "Computer Science / IT", sourceUrl: "https://example-demo.local/mcq/demo-020" },
  { sourceQuestionId: "demo-021", question: "Which of the following is used to prevent unauthorized access to a network?", optionA: "Firewall", optionB: "Browser", optionC: "Compiler", optionD: "Spreadsheet", rawAnswerText: "Answer: A", subjectHint: "Computer Science / IT", sourceUrl: "https://example-demo.local/mcq/demo-021" },
  { sourceQuestionId: "demo-022", question: "The office record kept for tracking incoming and outgoing letters is called a:", optionA: "Ledger", optionB: "Dispatch register", optionC: "Balance sheet", optionD: "Invoice", rawAnswerText: "Answer: B", subjectHint: "Office/Clerical Knowledge", sourceUrl: "https://example-demo.local/mcq/demo-022" },
  { sourceQuestionId: "demo-023", question: "A file containing a record of all changes made to a document, often used in office correspondence, is called a:", optionA: "Draft", optionB: "Minute sheet", optionC: "Memo", optionD: "Circular", rawAnswerText: "Ans: B", subjectHint: "Office/Clerical Knowledge", sourceUrl: "https://example-demo.local/mcq/demo-023" },
  { sourceQuestionId: "demo-024", question: "Which of the following is Pakistan's largest province by area?", optionA: "Punjab", optionB: "Sindh", optionC: "Balochistan", optionD: "Khyber Pakhtunkhwa", rawAnswerText: "Answer: C", subjectHint: "Pakistan Studies", sourceUrl: "https://example-demo.local/mcq/demo-024" },
  { sourceQuestionId: "demo-025", question: "Choose the correct antonym of \"Optimist\".", optionA: "Pessimist", optionB: "Realist", optionC: "Idealist", optionD: "Activist", rawAnswerText: "Answer: A", subjectHint: "English", sourceUrl: "https://example-demo.local/mcq/demo-025" }
];
